# docker-compose.yml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  # 本番用のDockerfile
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    command: bash -c "bundle exec rails db:migrate && bundle exec rails assets:precompile && bundle exec rails server -b 0.0.0.0"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: fishdrip_production

volumes:
  postgres_data:
