# docker-compose.override.yml
services:
  web:
    build:
      dockerfile: Dockerfile.dev  # 開発用のDockerfile
    environment:
      - RAILS_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
    volumes:
      - .:/app
    command: bash -c "bundle exec rails db:create db:migrate && bundle exec rails server -b 0.0.0.0"

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fishdrip_development
    volumes:
      - postgres_data:/var/lib/postgresql/data