name: Run model tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  model-spec:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@localhost:5432/test_db

    steps:
      - uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.8
          bundler-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libvips postgresql-client
          bundle install

      - name: Setup database
        run: |
          cp config/database.yml.github config/database.yml
          bin/rails db:create
          bin/rails db:schema:load

      - name: Run model specs only
        run: bundle exec rspec spec/models
